# Generated by Django 2.2.24 on 2023-05-20 15:37

from django.db import migrations, models


def set_new_building(apps, schema_editor):
    flats_to_update = apps.get_model('property', 'Flat').objects.all()

    for flat in flats_to_update:
        if flat.construction_year >= 2015:
            flat.new_building = 1
        else:
            flat.new_building = 0
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, max_length=5, null=True, verbose_name='Новостройка'),
        ),
        migrations.RunPython(set_new_building),
    ]
