# Generated by Django 2.2.24 on 2023-05-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20230520_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.CharField(blank=True, choices=[('', 'Неизвестно'), (True, 'Да'), (False, 'Нет')], db_index=True, max_length=5, null=True, verbose_name='Новостройка'),
        ),
    ]
