# Generated by Django 2.2.24 on 2023-05-20 19:07

from django.db import migrations


def set_new_building(apps, schema_editor):
    flats_to_update = apps.get_model('property', 'Flat').objects.all()

    for flat in flats_to_update:
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230520_2214'),
    ]

    operations = [
        migrations.RunPython(set_new_building),
    ]
